<a href="https://colab.research.google.com/github/Adaline-K/git4-collaboration-sourcetree/blob/master/data_test02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**넘파이(NumPy) 배열 프로그래밍**

-배열과 리스트의 차이점을 알고 배열을 사용하는 이유를 이해한다.

-배열을 생성하고 다루는 방법을 익힌다.

-넘파이를 사용하여 기술 통계를 낼 수 있다.

-난수를 발생시키고 그 결과를 분석하는 방법을 공부한다.




In [ ]:
#NumPy 패키지사용하여 배열(Array)프로그래밍
import numpy as np

ar= np.array([0,1,2,3,4,5,6,7,8,9])
ar


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
data =[0,1,2,3,4,5,6,7,8,9]

answer=[]
for di in data:
   answer.append(2*data[di])
print(answer)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [ ]:
x=np.array(data)
print(x)
print(2*x)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
L=[0,1,2,3,4,5,6,7,8,9]
print(2*L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
a=np.array([1,2,3])
b=np.array([10,20,30])

print(2*a+b)

[12 24 36]


In [ ]:
a==2

array([False,  True, False])

In [ ]:
b>10

array([False,  True,  True])

In [ ]:
(a==2)&(b>10)

array([False,  True, False])

In [ ]:
c=np.array([[0,1,2],[3,4,5]])
print(c)
print(len(c))
print(len(c[0]))


[[0 1 2]
 [3 4 5]]
2
3


In [ ]:
d=np.array([[10,20,30,40], [50,60,70,80]])
print(d)
print(len(d))
print(len(d[0]))

[[10 20 30 40]
 [50 60 70 80]]
2
4


In [ ]:
e=np.array([[[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]],
            [[11,12,13,14],
              [15,16,17,18],
             [19,20,21,22]]])
print(len(e))
print(len(e[0]))
print(len(e[0][0]))
print()
print(e.ndim)
print(e.shape)


2
3
4

3
(2, 3, 4)


In [ ]:
a=np.array([0,1,2,3,4])
print(a[2])
print(a[-1])
print()

b=np.array([[10,20,30,40], [50,60,70,80]])
print(b[0][0])
print(b[1][3])
print(b[-1][-1])

In [ ]:
a=np.array([[0,1,2],[3,4,5]])
print(a)
print(a[1][1])
print(a[0,:])
print(a[1,1:])

[[0 1 2]
 [3 4 5]]
4
[0 1 2]
[4 5]


In [ ]:
#fancy indexing
a= np.array([0,1,2,3,4,5,6,7,8,9])
idx=np.array([True, False, True, False, True,
              False, True, False, True, False])
a[idx]

print(a%2)
print()
print(a%2==0)
print()
print(a[a%2==0])


[0 1 0 1 0 1 0 1 0 1]

[ True False  True False  True False  True False  True False]

[0 2 4 6 8]


In [ ]:
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(a)
print(a[:,[True,False,False,True]])
print()
print(a[[2,0,1],:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [ ]:
x=np.array([1,2,3])
print(x.dtype)

y=np.array([1,2,3.0])
print(y.dtype)

a=np.array([1,2,3], dtype='f')
a.dtype
print()

print(a[0]+a[1])
b=np.array([1,2,3], dtype='U')
b.dtype
print(b[0]+b[1])


int64
float64

3.0
12


In [ ]:
d=np.array([0,1,-1,0])/np.array([1,0,0,0])
d

In [ ]:
a=np.zeros((2,3)) #0행렬
print(a)
print()

b=np.zeros(5, dtype='f')
b

[[0. 0. 0.]
 [0. 0. 0.]]



array([0., 0., 0., 0., 0.], dtype=float32)

In [ ]:
e=np.ones((2,3,4), dtype="i8") #1행렬
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
g=np.empty((4,3)) #배열 초기화
g

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323],
       [3.5e-323, 4.0e-323, 4.4e-323],
       [4.9e-323, 5.4e-323, 5.9e-323]])

In [ ]:
#range처럼 리스트를 만듦
f=np.arange(10)
ff=np.arange(3, 21,2)
ff

s=np.linspace(0,100,5) #5개로 나눔
ss=np.logspace(0.1, 1,10)
ss

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [ ]:
#전치행렬(Transpose: 행과 열을 바꾸는 행렬)
A= np.array([[1,2,3], [4,5,6]])
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a=np.arange(12)
print(a)
b=a.reshape(3,-1)
print(b)

c=a.reshape(2,2,-1)
print(c)

d=a.reshape(2,-1,2)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
x=np.arange(5)
print(x)
y=x.reshape(5,1)
y

[0 1 2 3 4]


array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
#행렬 연결하기 hstack, vstack
a1=np.ones((2,3))
a2=np.zeros((3,3))

a3=np.vstack([a1,a2])
a3

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a=np.array([[0,1,2],[3,4,5]])
np.tile(a,2)
np.tile(a,(3,2)) #행은 3배, 열은 2배


array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [ ]:
x=np.arange(3)
y=np.arange(5)

print(x)
print(y)
print()

X,Y=np.meshgrid(x,y)
print(X)
print()
print(Y)

print()
[list(zip(x,y)) for x,y in zip(X,Y)]

[0 1 2]
[0 1 2 3 4]

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]



[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [ ]:
#배열의 연산
x=np.arange(1,10001)
y=np.arange(10001,20001)


z=np.zeros_like(x)
for i in range(10000):
  z[i]=x[i]+y[i]



In [ ]:
a=np.array([1,2,3,4])
b=np.array([4,2,2,4])

np.all(a==b)

False

In [ ]:
x=np.arange(10)
100*x
y=np.arange(12).reshape(3,4)
y
y*100

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [ ]:
#브로드캐스팅(크기가 다른 행렬의 연산)
x=np.arange(5)
y=np.ones_like(x)
print(x+y)
print(x+1)

[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
x=np.vstack([range(7)[i:i +3] for i in range(5)])
y=np.arange(5)[:, np.newaxis]
print(x)
print(y)
print(x+y)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 0  1  2]
 [ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]


In [ ]:
x=np.array([1,2,3,1])
print(x.sum())
print(x.min())
print(x.max())
print(x.argmin()) #최소값의 위치
print(x.argmax()) #최대값의 위치
print(x.mean()) #평균
np.median(x)
np.all([True, True,False])


7
1
3
0
2
1.75


False

In [ ]:
a=np.zeros((100,100), dtype=np.int)
print(np.any(a!=0))
print(np.all(a==a))

False
True


In [ ]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])

((a <=b) & (b <=c)).all()

True

In [ ]:
x=np.array([[1,1], [2,2]])
print(x)
print(x.sum())
print(x.sum(axis=0)) #열합계
print()
print(x.sum(axis=1)) #행합계


[[1 1]
 [2 2]]
6
[3 3]

[2 4]


In [ ]:
#정렬
a= np.array([[4,3,5,7],
             [1,12,11,9],
             [2,15,1,14]])

np.sort(a) #axis=1 or axis=-1 (행기준)
np.sort(a, axis=0) #열기준

a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [ ]:
a=np.array([42,38,12,25])
j=np.argsort(a) #정렬의 순서
print(j)
print(a[j])

[2 3 1 0]
[12 25 38 42]


In [ ]:
#Descriptive Statistics

x=np.array([18,5,10,23,19,-8,10,0,0,
            2,5,4,15,-1,4,-7,-24,7])
print(len(x))
print(np.mean(x))
print(np.sum(x))
print(np.var(x)) #분산
print()
np.var(x,ddof=1)

18
4.555555555555555
82
116.13580246913583



122.96732026143793

In [ ]:
y=np.array([18,5,10,23,19,-8,10,0,0,
            2,5,4,15,-1,4,-7,-24,7])

print(np.var(y))
print(np.std(x))
print()
print(np.max(y))
print(np.min(y))
print()
print(np.median(x))

116.13580246913583
10.77663224152777

23
-24

4.5


In [ ]:
#사분위수(quartile): 데이터를 가장 작은 수부터 가장 큰수까지 크기가 커지는 순서대로 정렬하였을때,
# 각각 1사분위수, 2사분위수, 3사분위수로 정하고, 1/4의 위치

y=np.array([18,5,10,23,19,-8,10,0,0,
            2,5,4,15,-1,4,-7,-24,7])

np.percentile(x,0)
np.percentile(x,25)
np.percentile(x,50)
np.percentile(x,75)
np.percentile(x,100)

23.0

In [ ]:
np.random.rand(10)

array([0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703,
       0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781])

In [ ]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
#데이터 순서바꾸기
x=np.arange(10)
print(x)
np.random.shuffle(x) 
x

[0 1 2 3 4 5 6 7 8 9]


array([5, 2, 3, 4, 1, 0, 9, 8, 7, 6])

In [ ]:
#데이터 샘플링
np.random.choice(5,3,replace=False)

array([2, 4, 1])

In [ ]:
np.random.choice(5,10, p=[0.1,0,0.3,0.6,0])

array([2, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:

np.random.randn(3,5)

array([[-0.49114966,  0.71267817,  1.11334035, -2.15367459, -0.41611148],
       [-1.07089699,  0.22113881, -1.12305712, -1.05075796,  1.01207905],
       [ 1.54371643, -0.40211489,  0.8647491 , -0.22686923,  0.81116027]])

In [ ]:
np.random.randint(10,20,size=10)

array([10, 14, 13, 16, 19, 18, 10, 18, 15, 19])