<a href="https://colab.research.google.com/github/Adaline-K/git4-collaboration-sourcetree/blob/master/pytotest01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from __future__ import print_function
import torch



In [5]:
x= torch.empty(5,3)
print(x)

tensor([[3.3144e-36, 0.0000e+00, 2.3694e-38],
        [6.2382e+26, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [6]:
x=torch.rand(5,3)
print(x)

tensor([[0.3742, 0.9642, 0.6435],
        [0.0624, 0.1028, 0.1867],
        [0.1184, 0.2271, 0.1448],
        [0.8124, 0.2921, 0.7791],
        [0.0969, 0.7414, 0.3620]])


In [8]:
x=torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x=x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [13]:
x=torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.1360, -0.4301, -0.9714],
        [ 0.2258, -0.9006, -1.0489],
        [-0.2819, -1.5775,  0.3899],
        [ 0.2593,  0.3689,  0.2558],
        [-0.3542, -0.6209, -0.8489]])


In [14]:
print(x.size())

torch.Size([5, 3])


In [16]:
y=torch.rand(5,3)
print(x+y)

tensor([[ 0.4538, -0.0624, -0.0636],
        [ 0.2476,  0.0021, -0.4286],
        [ 0.2579, -1.5305,  0.5432],
        [ 1.1774,  1.3483,  0.4218],
        [ 0.3227, -0.4499, -0.3596]])


In [17]:
print(torch.add(x,y))

tensor([[ 0.4538, -0.0624, -0.0636],
        [ 0.2476,  0.0021, -0.4286],
        [ 0.2579, -1.5305,  0.5432],
        [ 1.1774,  1.3483,  0.4218],
        [ 0.3227, -0.4499, -0.3596]])


In [18]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[ 0.4538, -0.0624, -0.0636],
        [ 0.2476,  0.0021, -0.4286],
        [ 0.2579, -1.5305,  0.5432],
        [ 1.1774,  1.3483,  0.4218],
        [ 0.3227, -0.4499, -0.3596]])


In [19]:
y.add_(x)
print(y)

tensor([[ 0.4538, -0.0624, -0.0636],
        [ 0.2476,  0.0021, -0.4286],
        [ 0.2579, -1.5305,  0.5432],
        [ 1.1774,  1.3483,  0.4218],
        [ 0.3227, -0.4499, -0.3596]])


In [21]:
x= torch.randn(4,4)
y= x.view(16)
z= x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
print(x)

tensor([[ 0.4634, -0.3350, -1.1435, -1.7606],
        [-1.2990, -0.2985,  0.4700,  1.0161],
        [ 1.0735,  1.4455,  0.9557,  0.2254],
        [ 0.3676, -0.9835,  0.0428,  1.6866]])


In [23]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([-0.8518])
-0.8518206477165222


In [24]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([-1.5713])
-1.571345329284668


In [28]:
#Numpy 변환(Bridge)
#Torch Tensor를 Numpy 배열(array)로 변환

a= torch.ones(5)
print(a)


tensor([1., 1., 1., 1., 1.])


In [29]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [31]:
a.add_(1)
print(a)
print(b) #Numpy로 변한 a

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [32]:
#Numpy 배열을 Torch Tensor로 변환
import numpy as np

a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
#자동미분
