<a href="https://colab.research.google.com/github/Adaline-K/git4-collaboration-sourcetree/blob/master/tensortest5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#라이브러리 사용
import tensorflow as tf
import pandas as pd

In [5]:
#보스턴 집값 예측
#과거 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)

#종속, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
(506, 13) (506, 1)


In [6]:
#모델구조만들기
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [7]:
#모델구조확인
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [15]:
#데이터로 모델학습시키기(FIT)
model.fit(독립, 종속, epochs=20)


Epoch 1/20
16/16 [==============================] - 0s 1ms/step - loss: 20.7857
Epoch 2/20
16/16 [==============================] - 0s 1ms/step - loss: 21.3204
Epoch 3/20
16/16 [==============================] - 0s 1ms/step - loss: 20.9954
Epoch 4/20
16/16 [==============================] - 0s 1ms/step - loss: 21.5238
Epoch 5/20
16/16 [==============================] - 0s 1ms/step - loss: 20.7231
Epoch 6/20
16/16 [==============================] - 0s 1ms/step - loss: 21.6188
Epoch 7/20
16/16 [==============================] - 0s 1ms/step - loss: 21.4435
Epoch 8/20
16/16 [==============================] - 0s 1ms/step - loss: 20.9751
Epoch 9/20
16/16 [==============================] - 0s 1ms/step - loss: 21.8173
Epoch 10/20
16/16 [==============================] - 0s 1ms/step - loss: 21.2402
Epoch 11/20
16/16 [==============================] - 0s 1ms/step - loss: 21.9554
Epoch 12/20
16/16 [==============================] - 0s 1ms/step - loss: 21.5781
Epoch 13/20
16/16 [==================

In [16]:
#모델이용
print(model.predict(독립[0:5]))
print(종속[0:5])


[[30.463396]
 [23.097076]
 [30.425547]
 [33.349503]
 [31.122194]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [21]:
#아이리스 품종 분류
#과거의 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

#원핫인코딩
아이리스 = pd.get_dummies(아이리스)
print(아이리스.columns)
#독립, 종속변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(독립.shape, 종속.shape)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')
(150, 4) (150, 3)


In [27]:
#모델구조 만들기
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [28]:
#모델구조 확인
model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_10 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_11 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_12 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_13 (Dense)             (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [29]:
#데이터로 모델 학습시키기(FIT)
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 3ms/step - loss: 2.1392 - accuracy: 0.3069
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 1.7100 - accuracy: 0.3498
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 1.5584 - accuracy: 0.3485
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 1.3953 - accuracy: 0.3668
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 1.3804 - accuracy: 0.2999
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 1.2665 - accuracy: 0.3307
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 1.2082 - accuracy: 0.3376
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 1.1819 - accuracy: 0.2438
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 1.1457 - accuracy: 0.1342
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 1.1177 - accuracy: 0.1995
Epoch 11/100
5/5 [===========

In [26]:
#모델이용
print(model.predict(독립[0:5]))
print(종속[0:5])

[[9.9812514e-01 4.5377540e-04 1.4210468e-03]
 [9.9695933e-01 1.1155244e-03 1.9252517e-03]
 [9.9728930e-01 7.5782376e-04 1.9529337e-03]
 [9.9620759e-01 1.4456611e-03 2.3468148e-03]
 [9.9808609e-01 4.3015435e-04 1.4838669e-03]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
