<a href="https://colab.research.google.com/github/Adaline-K/git4-collaboration-sourcetree/blob/master/tensortest4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
#라이브러리 사용
import tensorflow as tf
import pandas as pd

In [41]:
#1.과거의 데이터 준비
파일경로='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [42]:
#2.원핫인코딩
아이리스= pd.get_dummies(아이리스)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [43]:
#4.독립변수, 종속변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [46]:
#5.모델의 구조 만들기
X= tf.keras.layers.Input(shape=[4])
Y= tf.keras.layers.Dense(3, activation='softmax')(X)
model= tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [48]:
#데이터로 모델을 fit하기
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1601 - accuracy: 0.9667
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1589 - accuracy: 0.9667
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1589 - accuracy: 0.9667
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1589 - accuracy: 0.9667
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1588 - accuracy: 0.9667
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1586 - accuracy: 0.9667
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1589 - accuracy: 0.9667
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1584 - accuracy: 0.9667
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1584 - accuracy: 0.9667
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1582 - accuracy: 0.9667


In [54]:
#모델을 이용하기
print(model.predict(독립[0:5]))
print(종속[0:5])

[[9.9908888e-01 9.1098424e-04 7.5498107e-08]
 [9.9420071e-01 5.7983301e-03 9.6820429e-07]
 [9.9829358e-01 1.7061923e-03 2.8162560e-07]
 [9.9607348e-01 3.9254827e-03 1.1221829e-06]
 [9.9943906e-01 5.6086946e-04 5.0032504e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [52]:
print(model.predict(독립[-5:]))
print(종속[-5:])

[[1.40048940e-06 1.17088065e-01 8.82910550e-01]
 [2.15625369e-06 2.15365872e-01 7.84631968e-01]
 [6.57451346e-06 2.20318645e-01 7.79674768e-01]
 [3.14791509e-06 5.81460260e-02 9.41850901e-01]
 [2.20103211e-05 2.11968422e-01 7.88009584e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [53]:
#weights & bias출력
print(model.get_weights())

[array([[-0.06537103,  0.75068486, -0.7758171 ],
       [ 3.4004586 , -0.6373719 , -1.4278445 ],
       [-2.9374204 , -0.37105325,  1.2165958 ],
       [-4.4973583 , -1.9939612 ,  1.5453589 ]], dtype=float32), array([ 1.812447 ,  0.6893017, -1.0876306], dtype=float32)]
